/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as WordBankIndexRouteImport } from './routes/word-bank.index'
import { Route as WordBankMovieIdRouteImport } from './routes/word-bank.$movieId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const WordBankIndexRoute = WordBankIndexRouteImport.update({
  id: '/word-bank/',
  path: '/word-bank/',
  getParentRoute: () => rootRouteImport,
} as any)
const WordBankMovieIdRoute = WordBankMovieIdRouteImport.update({
  id: '/word-bank/$movieId',
  path: '/word-bank/$movieId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/review': typeof ReviewRoute
  '/word-bank/$movieId': typeof WordBankMovieIdRoute
  '/word-bank/': typeof WordBankIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/review': typeof ReviewRoute
  '/word-bank/$movieId': typeof WordBankMovieIdRoute
  '/word-bank': typeof WordBankIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/review': typeof ReviewRoute
  '/word-bank/$movieId': typeof WordBankMovieIdRoute
  '/word-bank/': typeof WordBankIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/review' | '/word-bank/$movieId' | '/word-bank/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/review' | '/word-bank/$movieId' | '/word-bank'
  id: '__root__' | '/' | '/review' | '/word-bank/$movieId' | '/word-bank/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReviewRoute: typeof ReviewRoute
  WordBankMovieIdRoute: typeof WordBankMovieIdRoute
  WordBankIndexRoute: typeof WordBankIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/word-bank/': {
      id: '/word-bank/'
      path: '/word-bank'
      fullPath: '/word-bank/'
      preLoaderRoute: typeof WordBankIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/word-bank/$movieId': {
      id: '/word-bank/$movieId'
      path: '/word-bank/$movieId'
      fullPath: '/word-bank/$movieId'
      preLoaderRoute: typeof WordBankMovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReviewRoute: ReviewRoute,
  WordBankMovieIdRoute: WordBankMovieIdRoute,
  WordBankIndexRoute: WordBankIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
